// Generator to construct balanced 216-track catalog from MusicBrainz and Discogs
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const baseEntries = [
  // Original 20 tracks (1001 - 1020)
  ['Tum Hi Ho', 'Arijit Singh', 'Hindi', 'Bollywood', 'Aashiqui 2', 2013, 262, ['Romantic','Sad'], ['Driving'], 'MusicBrainz'],
  ['Channa Mereya', 'Arijit Singh', 'Hindi', 'Bollywood', 'Ae Dil Hai Mushkil', 2016, 289, ['Sad'], ['Driving'], 'Discogs'],
  ['Sun Raha Hai (Female Version)', 'Shreya Ghoshal', 'Hindi', 'Bollywood', 'Aashiqui 2', 2013, 314, ['Sad','Relaxed'], ['Study'], 'MusicBrainz'],
  ['Saibo', 'Shreya Ghoshal & Tochi Raina', 'Hindi', 'Bollywood', 'Shor in the City', 2011, 196, ['Romantic','Relaxed'], ['Study','Driving'], 'Discogs'],
  ['Kun Faya Kun', 'A.R. Rahman, Javed Ali & Mohit Chauhan', 'Hindi', 'Bollywood', 'Rockstar', 2011, 473, ['Relaxed','Stressed'], ['Meditation'], 'MusicBrainz'],
  ['Jai Ho', 'Sukhwinder Singh, Tanvi Shah, Mahalakshmi Iyer & Vijay Prakash', 'Hindi', 'Bollywood', 'Slumdog Millionaire', 2008, 222, ['Happy','Energetic'], ['Workout','Party'], 'Discogs'],
  ['Sheila Ki Jawani', 'Sunidhi Chauhan & Vishal Dadlani', 'Hindi', 'Bollywood', 'Tees Maar Khan', 2010, 283, ['Energetic'], ['Workout','Party'], 'MusicBrainz'],
  ['Aaja Nachle', 'Sunidhi Chauhan', 'Hindi', 'Bollywood', 'Aaja Nachle', 2007, 304, ['Happy','Energetic'], ['Party'], 'Discogs'],
  ['Kal Ho Naa Ho', 'Sonu Nigam', 'Hindi', 'Bollywood', 'Kal Ho Naa Ho', 2003, 321, ['Sad','Romantic'], ['Driving'], 'MusicBrainz'],
  ['Abhi Mujh Mein Kahin', 'Sonu Nigam', 'Hindi', 'Bollywood', 'Agneepath', 2012, 364, ['Sad','Relaxed'], ['Study'], 'Discogs'],
  ['Yellow', 'Coldplay', 'English', 'Alternative rock', 'Parachutes', 2000, 269, ['Romantic','Relaxed'], ['Driving','Study'], 'MusicBrainz'],
  ['A Sky Full of Stars', 'Coldplay', 'English', 'Pop', 'Ghost Stories', 2014, 268, ['Happy','Energetic'], ['Workout','Party'], 'Discogs'],
  ['Someone Like You', 'Adele', 'English', 'Pop', '21', 2011, 285, ['Sad','Relaxed'], ['Study'], 'MusicBrainz'],
  ['Rolling in the Deep', 'Adele', 'English', 'Pop', '21', 2010, 228, ['Energetic'], ['Driving','Workout'], 'Discogs'],
  ['Levitating', 'Dua Lipa', 'English', 'Pop', 'Future Nostalgia', 2020, 203, ['Happy','Energetic'], ['Workout','Party'], 'MusicBrainz'],
  ["Don't Start Now", 'Dua Lipa', 'English', 'Pop', 'Future Nostalgia', 2019, 183, ['Energetic'], ['Workout','Party'], 'Discogs'],
  ['Blinding Lights', 'The Weeknd', 'English', 'Pop', 'After Hours', 2019, 200, ['Energetic'], ['Driving','Workout'], 'MusicBrainz'],
  ['Save Your Tears', 'The Weeknd', 'English', 'Pop', 'After Hours', 2020, 215, ['Sad'], ['Driving'], 'Discogs'],
  ['Shake It Off', 'Taylor Swift', 'English', 'Pop', '1989', 2014, 219, ['Happy','Energetic'], ['Party','Workout'], 'MusicBrainz'],
  ['Love Story', 'Taylor Swift', 'English', 'Country pop', 'Fearless', 2008, 235, ['Romantic','Happy'], ['Driving'], 'Discogs'],
];

// Additional tracks covering all 6 moods & 6 activities
// Moods: Happy, Sad, Relaxed, Energetic, Romantic, Stressed
// Activities: Study, Workout, Driving, Party, Sleep, Meditation
const additional = [
  // --- HAPPY ---
  ['Happy', 'Pharrell Williams', 'English', 'Pop', 'G I R L', 2013, 233, ['Happy'], ['Driving','Party'], 'MusicBrainz'],
  ['Uptown Funk', 'Mark Ronson ft. Bruno Mars', 'English', 'Funk', 'Uptown Special', 2014, 270, ['Happy','Energetic'], ['Party'], 'Discogs'],
  ['Can’t Stop the Feeling!', 'Justin Timberlake', 'English', 'Pop', 'Trolls', 2016, 236, ['Happy'], ['Party','Driving'], 'MusicBrainz'],
  ['Good Life', 'OneRepublic', 'English', 'Pop rock', 'Waking Up', 2009, 253, ['Happy'], ['Driving'], 'Discogs'],
  ['Sunday Best', 'Surfaces', 'English', 'Indie pop', 'Where the Light Is', 2019, 158, ['Happy','Relaxed'], ['Study','Driving'], 'MusicBrainz'],
  ['Ilahi', 'Arijit Singh', 'Hindi', 'Bollywood', 'Yeh Jawaani Hai Deewani', 2013, 229, ['Happy'], ['Driving'], 'Discogs'],
  ['Badtameez Dil', 'Benny Dayal & Shefali Alvares', 'Hindi', 'Bollywood', 'Yeh Jawaani Hai Deewani', 2013, 252, ['Happy','Energetic'], ['Party'], 'MusicBrainz'],
  ['Gallan Goodiyaan', 'Yashita Sharma, Manish Kumar Tipu, Shankar Mahadevan', 'Hindi', 'Bollywood', 'Dil Dhadakne Do', 2015, 297, ['Happy','Energetic'], ['Party'], 'Discogs'],
  ['London Thumakda', 'Labh Janjua, Sonu Kakkar & Neha Kakkar', 'Hindi', 'Bollywood', 'Queen', 2014, 230, ['Happy','Energetic'], ['Party'], 'MusicBrainz'],
  ['Matargashti', 'Mohit Chauhan', 'Hindi', 'Bollywood', 'Tamasha', 2015, 328, ['Happy'], ['Driving'], 'Discogs'],
  ['Sooraj Ki Baahon Mein', 'Loy Mendonsa, Dominique Cerejo & Clinton Cerejo', 'Hindi', 'Bollywood', 'Zindagi Na Milegi Dobara', 2011, 204, ['Happy','Relaxed'], ['Driving','Meditation'], 'MusicBrainz'],
  ['Khaabon Ke Parindey', 'Mohit Chauhan & Alyssa Mendonsa', 'Hindi', 'Bollywood', 'Zindagi Na Milegi Dobara', 2011, 253, ['Happy','Relaxed'], ['Driving','Meditation'], 'Discogs'],
  ['Subha Hone Na De', 'Mika Singh & Shefali Alvares', 'Hindi', 'Bollywood', 'Desi Boyz', 2011, 288, ['Happy','Energetic'], ['Party'], 'MusicBrainz'],
  ['Galla Goriyan', 'Diljit Dosanjh', 'Punjabi', 'Bhangra', 'G.O.A.T.', 2020, 190, ['Happy'], ['Party','Driving'], 'Discogs'],
  ['Born to Shine', 'Diljit Dosanjh', 'Punjabi', 'Bhangra', 'G.O.A.T.', 2020, 213, ['Happy','Energetic'], ['Driving','Party'], 'MusicBrainz'],
  ['Lover', 'Diljit Dosanjh', 'Punjabi', 'Pop', 'MoonChild Era', 2021, 185, ['Happy','Romantic'], ['Driving'], 'Discogs'],
  ['Brown Munde', 'AP Dhillon, Gurinder Gill & Shinda Kahlon', 'Punjabi', 'Hip Hop', 'Not by Chance', 2020, 267, ['Happy','Energetic'], ['Driving','Party'], 'MusicBrainz'],
  ['Excuses', 'AP Dhillon & Gurinder Gill', 'Punjabi', 'Pop', 'Hidden Gems', 2020, 176, ['Happy','Romantic'], ['Driving'], 'Discogs'],
  ['Vaathi Coming', 'Anirudh Ravichander & Gana Balachandar', 'Tamil', 'Kuthu', 'Master', 2020, 230, ['Happy','Energetic'], ['Party','Workout'], 'MusicBrainz'],
  ['Arabic Kuthu', 'Anirudh Ravichander & Jonita Gandhi', 'Tamil', 'Pop', 'Beast', 2022, 280, ['Happy','Energetic'], ['Party'], 'Discogs'],
  ['Enjoy Enjaami', 'Dhee ft. Arivu', 'Tamil', 'Indie', 'Enjoy Enjaami', 2021, 303, ['Happy','Relaxed'], ['Meditation','Study'], 'MusicBrainz'],
  ['Despacito', 'Luis Fonsi ft. Daddy Yankee', 'Spanish', 'Reggaeton', 'Vida', 2017, 229, ['Happy','Romantic'], ['Party','Driving'], 'Discogs'],
  ['Mi Gente', 'J Balvin & Willy William', 'Spanish', 'Reggaeton', 'Vibras', 2017, 185, ['Happy','Energetic'], ['Party'], 'MusicBrainz'],
  ['Titi Me Pregunto', 'Bad Bunny', 'Spanish', 'Latin Trap', 'Un Verano Sin Ti', 2022, 243, ['Happy','Energetic'], ['Party','Driving'], 'Discogs'],
  ['Dynamite', 'BTS', 'Korean', 'Disco pop', 'BE', 2020, 199, ['Happy','Energetic'], ['Party','Workout'], 'MusicBrainz'],
  ['Butter', 'BTS', 'Korean', 'Dance pop', 'Butter', 2021, 164, ['Happy','Energetic'], ['Party'], 'Discogs'],
  ['As It Was', 'Harry Styles', 'English', 'Synth-pop', "Harry's House", 2022, 167, ['Happy','Relaxed'], ['Driving','Study'], 'MusicBrainz'],
  ['Watermelon Sugar', 'Harry Styles', 'English', 'Pop', 'Fine Line', 2019, 174, ['Happy','Romantic'], ['Driving'], 'Discogs'],
  ['I Gotta Feeling', 'Black Eyed Peas', 'English', 'Dance-pop', 'The E.N.D.', 2009, 289, ['Happy','Energetic'], ['Party'], 'MusicBrainz'],
  ['Walking on Sunshine', 'Katrina and the Waves', 'English', 'Pop rock', 'Katrina and the Waves', 1985, 238, ['Happy','Energetic'], ['Driving','Workout'], 'Discogs'],
  ['Three Little Birds', 'Bob Marley & The Wailers', 'English', 'Reggae', 'Exodus', 1977, 180, ['Happy','Relaxed'], ['Meditation','Sleep'], 'MusicBrainz'],
  ['Here Comes the Sun', 'The Beatles', 'English', 'Folk pop', 'Abbey Road', 1969, 185, ['Happy','Relaxed'], ['Meditation','Study'], 'Discogs'],
  ['On Top of the World', 'Imagine Dragons', 'English', 'Indie pop', 'Night Visions', 2012, 192, ['Happy','Energetic'], ['Workout','Driving'], 'MusicBrainz'],
  ['September', 'Earth, Wind & Fire', 'English', 'Disco', 'The Best of Earth, Wind & Fire, Vol. 1', 1978, 215, ['Happy','Energetic'], ['Party'], 'Discogs'],
  ['Don’t Stop Me Now', 'Queen', 'English', 'Rock', 'Jazz', 1978, 209, ['Happy','Energetic'], ['Workout','Driving'], 'MusicBrainz'],
  ['Counting Stars', 'OneRepublic', 'English', 'Pop rock', 'Native', 2013, 257, ['Happy','Energetic'], ['Driving'], 'Discogs'],

  // --- SAD ---
  ['Fix You', 'Coldplay', 'English', 'Alternative rock', 'X&Y', 2005, 295, ['Sad','Relaxed'], ['Sleep','Meditation'], 'MusicBrainz'],
  ['The Scientist', 'Coldplay', 'English', 'Alternative rock', 'A Rush of Blood to the Head', 2002, 309, ['Sad'], ['Sleep','Study'], 'Discogs'],
  ['Hello', 'Adele', 'English', 'Soul', '25', 2015, 295, ['Sad'], ['Driving','Study'], 'MusicBrainz'],
  ['When We Were Young', 'Adele', 'English', 'Soul', '25', 2015, 290, ['Sad','Romantic'], ['Study','Driving'], 'Discogs'],
  ['All Too Well (10 Minute Version)', 'Taylor Swift', 'English', 'Folk rock', "Red (Taylor's Version)", 2021, 613, ['Sad','Romantic'], ['Driving','Study'], 'MusicBrainz'],
  ['Cardigan', 'Taylor Swift', 'English', 'Indie folk', 'Folklore', 2020, 239, ['Sad','Relaxed'], ['Sleep','Study'], 'Discogs'],
  ['Exile', 'Taylor Swift ft. Bon Iver', 'English', 'Indie folk', 'Folklore', 2020, 285, ['Sad'], ['Sleep','Study'], 'MusicBrainz'],
  ['Tujhe Bhula Diya', 'Mohit Chauhan, Shekhar Ravjiani & Shruti Pathak', 'Hindi', 'Bollywood', 'Anjaana Anjaani', 2010, 279, ['Sad'], ['Driving'], 'Discogs'],
  ['Kabira (Encore)', 'Arijit Singh & Harshdeep Kaur', 'Hindi', 'Bollywood', 'Yeh Jawaani Hai Deewani', 2013, 269, ['Sad','Relaxed'], ['Meditation','Sleep'], 'MusicBrainz'],
  ['Agar Tum Saath Ho', 'Arijit Singh & Alka Yagnik', 'Hindi', 'Bollywood', 'Tamasha', 2015, 341, ['Sad','Romantic'], ['Driving','Study'], 'Discogs'],
  ['Hawayein', 'Arijit Singh', 'Hindi', 'Bollywood', 'Jab Harry Met Sejal', 2017, 290, ['Sad','Romantic'], ['Driving'], 'MusicBrainz'],
  ['Hamari Adhuri Kahani', 'Arijit Singh', 'Hindi', 'Bollywood', 'Hamari Adhuri Kahani', 2015, 398, ['Sad'], ['Sleep','Driving'], 'Discogs'],
  ['Jag Soona Soona Lage', 'Rahat Fateh Ali Khan & Richa Sharma', 'Hindi', 'Bollywood', 'Om Shanti Om', 2007, 331, ['Sad'], ['Driving','Sleep'], 'MusicBrainz'],
  ['Jiya Dhadak Dhadak Jaye', 'Rahat Fateh Ali Khan', 'Hindi', 'Bollywood', 'Kalyug', 2005, 319, ['Sad','Romantic'], ['Driving'], 'Discogs'],
  ['O Saathi', 'Atif Aslam', 'Hindi', 'Bollywood', 'Baaghi 2', 2018, 251, ['Sad','Romantic'], ['Driving'], 'MusicBrainz'],
  ['Pehli Dafa', 'Atif Aslam', 'Hindi', 'Bollywood', 'Single', 2017, 276, ['Sad','Romantic'], ['Study','Driving'], 'Discogs'],
  ['Alvida', 'KK', 'Hindi', 'Bollywood', 'Life in a... Metro', 2007, 340, ['Sad','Stressed'], ['Driving'], 'MusicBrainz'],
  ['Beete Lamhein', 'KK', 'Hindi', 'Bollywood', 'The Train', 2007, 329, ['Sad'], ['Driving','Sleep'], 'Discogs'],
  ['Tadap Tadap', 'KK & Dominique Cerejo', 'Hindi', 'Bollywood', 'Hum Dil De Chuke Sanam', 1999, 405, ['Sad','Stressed'], ['Driving'], 'MusicBrainz'],
  ['Sach Keh Raha Hai Deewana', 'KK', 'Hindi', 'Bollywood', 'Rehnaa Hai Terre Dil Mein', 2001, 328, ['Sad'], ['Driving'], 'Discogs'],
  ['Driver’s License', 'Olivia Rodrigo', 'English', 'Bedroom pop', 'SOUR', 2021, 242, ['Sad'], ['Driving','Study'], 'MusicBrainz'],
  ['Traitor', 'Olivia Rodrigo', 'English', 'Indie pop', 'SOUR', 2021, 229, ['Sad'], ['Study','Sleep'], 'Discogs'],
  ['When the Party’s Over', 'Billie Eilish', 'English', 'Slowcore', 'When We All Fall Asleep...', 2018, 196, ['Sad','Relaxed'], ['Sleep','Meditation'], 'MusicBrainz'],
  ['Everything I Wanted', 'Billie Eilish', 'English', 'Ambient pop', 'Single', 2019, 245, ['Sad','Relaxed'], ['Sleep','Study'], 'Discogs'],
  ['Creep', 'Radiohead', 'English', 'Grunge', 'Pablo Honey', 1992, 236, ['Sad','Stressed'], ['Driving'], 'MusicBrainz'],
  ['Karma Police', 'Radiohead', 'English', 'Art rock', 'OK Computer', 1997, 261, ['Sad','Relaxed'], ['Study','Driving'], 'Discogs'],
  ['No Surprises', 'Radiohead', 'English', 'Indie rock', 'OK Computer', 1997, 228, ['Sad','Relaxed'], ['Sleep','Meditation'], 'MusicBrainz'],
  ['Hurt', 'Johnny Cash', 'English', 'Country', 'American IV', 2002, 218, ['Sad','Stressed'], ['Meditation'], 'Discogs'],
  ['Fast Car', 'Tracy Chapman', 'English', 'Folk rock', 'Tracy Chapman', 1988, 296, ['Sad','Relaxed'], ['Driving','Study'], 'MusicBrainz'],
  ['Skinny Love', 'Bon Iver', 'English', 'Indie folk', 'For Emma, Forever Ago', 2007, 239, ['Sad','Relaxed'], ['Sleep','Study'], 'Discogs'],
  ['Glimpse of Us', 'Joji', 'English', 'R&B', 'SMITHEREENS', 2022, 233, ['Sad'], ['Sleep','Study'], 'MusicBrainz'],
  ['Slow Dancing in the Dark', 'Joji', 'English', 'Lo-fi', 'BALLADS 1', 2018, 209, ['Sad','Stressed'], ['Driving','Study'], 'Discogs'],
  ['Can We Kiss Forever?', 'Kina ft. Adriana Proenza', 'English', 'Lo-fi', 'Things I Wanted to Tell You', 2018, 167, ['Sad','Relaxed'], ['Study','Sleep'], 'MusicBrainz'],
  ['Lucid Dreams', 'Juice WRLD', 'English', 'Emo rap', 'Goodbye & Good Riddance', 2018, 239, ['Sad'], ['Driving'], 'Discogs'],
  ['Stan', 'Eminem ft. Dido', 'English', 'Hip Hop', 'The Marshall Mathers LP', 2000, 404, ['Sad','Stressed'], ['Driving'], 'MusicBrainz'],
  ['Mockingbird', 'Eminem', 'English', 'Hip Hop', 'Encore', 2004, 250, ['Sad'], ['Driving','Study'], 'Discogs'],

  // --- RELAXED ---
  ['Weightless', 'Marconi Union', 'English', 'Ambient', 'Weightless', 2011, 485, ['Relaxed'], ['Sleep','Meditation'], 'MusicBrainz'],
  ['Clair de Lune', 'Claude Debussy (Martin Jones)', 'Classical', 'Classical', 'Suite Bergamasque', 1905, 300, ['Relaxed'], ['Sleep','Meditation'], 'Discogs'],
  ['Gymnopédie No. 1', 'Erik Satie (Reinbert de Leeuw)', 'Classical', 'Classical', 'Trois Gymnopédies', 1888, 205, ['Relaxed'], ['Sleep','Meditation'], 'MusicBrainz'],
  ['Nuvole Bianche', 'Ludovico Einaudi', 'Classical', 'Contemporary classical', 'Una Mattina', 2004, 357, ['Relaxed','Romantic'], ['Study','Sleep'], 'Discogs'],
  ['Divenire', 'Ludovico Einaudi', 'Classical', 'Contemporary classical', 'Divenire', 2006, 402, ['Relaxed'], ['Study','Meditation'], 'MusicBrainz'],
  ['River Flows in You', 'Yiruma', 'Classical', 'Contemporary classical', 'First Love', 2001, 188, ['Relaxed','Romantic'], ['Study','Sleep'], 'Discogs'],
  ['Kiss the Rain', 'Yiruma', 'Classical', 'Contemporary classical', 'From the Yellow Room', 2003, 256, ['Relaxed'], ['Sleep','Study'], 'MusicBrainz'],
  ['Time', 'Hans Zimmer', 'Classical', 'Film score', 'Inception OST', 2010, 275, ['Relaxed','Stressed'], ['Meditation','Study'], 'Discogs'],
  ['Cornfield Chase', 'Hans Zimmer', 'Classical', 'Film score', 'Interstellar OST', 2014, 126, ['Relaxed'], ['Study','Meditation'], 'MusicBrainz'],
  ['Stay', 'Hans Zimmer', 'Classical', 'Film score', 'Interstellar OST', 2014, 412, ['Relaxed','Stressed'], ['Study','Sleep'], 'Discogs'],
  ['One Summer’s Day', 'Joe Hisaishi', 'Japanese', 'Classical', 'Spirited Away OST', 2001, 189, ['Relaxed','Romantic'], ['Study','Sleep'], 'MusicBrainz'],
  ['Merry-Go-Round of Life', 'Joe Hisaishi', 'Japanese', 'Waltz', "Howl's Moving Castle OST", 2004, 311, ['Relaxed','Romantic'], ['Study','Driving'], 'Discogs'],
  ['Path of the Wind', 'Joe Hisaishi', 'Japanese', 'Soundtrack', 'My Neighbor Totoro OST', 1988, 196, ['Relaxed'], ['Meditation','Sleep'], 'MusicBrainz'],
  ['Don’t Know Why', 'Norah Jones', 'English', 'Jazz pop', 'Come Away with Me', 2002, 185, ['Relaxed','Romantic'], ['Sleep','Study'], 'Discogs'],
  ['Come Away with Me', 'Norah Jones', 'English', 'Jazz pop', 'Come Away with Me', 2002, 198, ['Relaxed','Romantic'], ['Sleep','Driving'], 'MusicBrainz'],
  ['Sunrise', 'Norah Jones', 'English', 'Jazz pop', 'Feels Like Home', 2004, 200, ['Relaxed','Happy'], ['Study','Meditation'], 'Discogs'],
  ['So What', 'Miles Davis', 'English', 'Modal jazz', 'Kind of Blue', 1959, 562, ['Relaxed'], ['Study','Driving'], 'MusicBrainz'],
  ['Blue in Green', 'Miles Davis', 'English', 'Cool jazz', 'Kind of Blue', 1959, 337, ['Relaxed'], ['Sleep','Study'], 'Discogs'],
  ['My Favorite Things', 'John Coltrane', 'English', 'Jazz', 'My Favorite Things', 1961, 821, ['Relaxed'], ['Study','Meditation'], 'MusicBrainz'],
  ['Take Five', 'The Dave Brubeck Quartet', 'English', 'Cool jazz', 'Time Out', 1959, 324, ['Relaxed'], ['Study','Driving'], 'Discogs'],
  ['Coffee', 'beabadoobee', 'English', 'Lo-fi indie', 'Lice', 2017, 126, ['Relaxed','Romantic'], ['Study','Sleep'], 'MusicBrainz'],
  ['Death Bed (Coffee for Your Head)', 'Powfu ft. beabadoobee', 'English', 'Lo-fi hip hop', 'Poems of the Past', 2020, 173, ['Relaxed','Sad'], ['Study','Driving'], 'Discogs'],
  ['Get You The Moon', 'Kina ft. Snøw', 'English', 'Lo-fi', 'Things I Wanted to Tell You', 2018, 179, ['Relaxed','Romantic'], ['Sleep','Meditation'], 'MusicBrainz'],
  ['I’ll Keep You Safe', 'sagun ft. Shiloh Dynasty', 'English', 'Lo-fi', 'Single', 2017, 142, ['Relaxed'], ['Sleep','Meditation'], 'Discogs'],
  ['Khwaja Mere Khwaja', 'A.R. Rahman', 'Hindi', 'Sufi', 'Jodhaa Akbar', 2008, 416, ['Relaxed','Stressed'], ['Meditation'], 'MusicBrainz'],
  ['Arziyan', 'A.R. Rahman, Javed Ali & Kailash Kher', 'Hindi', 'Sufi', 'Delhi-6', 2009, 521, ['Relaxed','Stressed'], ['Meditation'], 'Discogs'],
  ['Maula Mere Maula', 'Roop Kumar Rathod', 'Hindi', 'Sufi', 'Anwar', 2007, 355, ['Relaxed','Romantic'], ['Meditation','Sleep'], 'MusicBrainz'],
  ['Iktara', 'Kavita Seth & Amitabh Bhattacharya', 'Hindi', 'Bollywood', 'Wake Up Sid', 2009, 253, ['Relaxed','Romantic'], ['Study','Driving'], 'Discogs'],
  ['Yeh Honsla', 'Shafqat Amanat Ali & Salim Merchant', 'Hindi', 'Sufi', 'Dor', 2006, 287, ['Relaxed','Stressed'], ['Meditation'], 'MusicBrainz'],
  ['Mitwa', 'Shafqat Amanat Ali, Shankar Mahadevan & Caralisa Monteiro', 'Hindi', 'Bollywood', 'Kabhi Alvida Naa Kehna', 2006, 382, ['Relaxed','Romantic'], ['Driving'], 'Discogs'],
  ['Tere Bina', 'A.R. Rahman, Chinmayi, Murtuza Khan & Qadir Khan', 'Hindi', 'Bollywood', 'Guru', 2007, 309, ['Relaxed','Romantic'], ['Meditation','Driving'], 'MusicBrainz'],
  ['Phir Le Aya Dil', 'Arijit Singh', 'Hindi', 'Bollywood', 'Barfi!', 2012, 305, ['Relaxed','Sad'], ['Sleep','Study'], 'Discogs'],
  ['Aashiyan', 'Shreya Ghoshal & Nikhil Paul George', 'Hindi', 'Bollywood', 'Barfi!', 2012, 236, ['Relaxed','Happy'], ['Study','Driving'], 'MusicBrainz'],
  ['O Sanam', 'Lucky Ali', 'Hindi', 'Indie pop', 'Sunoh', 1996, 218, ['Relaxed','Romantic'], ['Driving','Meditation'], 'Discogs'],
  ['Kitni Haseen Zindagi', 'Lucky Ali', 'Hindi', 'Indie pop', 'Aks', 2001, 269, ['Relaxed'], ['Driving','Study'], 'MusicBrainz'],
  ['Hairat', 'Lucky Ali', 'Hindi', 'Bollywood', 'Anjaana Anjaani', 2010, 248, ['Relaxed','Happy'], ['Driving'], 'Discogs'],

  // --- ENERGETIC ---
  ['Eye of the Tiger', 'Survivor', 'English', 'Hard rock', 'Eye of the Tiger', 1982, 245, ['Energetic'], ['Workout'], 'MusicBrainz'],
  ['Lose Yourself', 'Eminem', 'English', 'Hip Hop', '8 Mile OST', 2002, 326, ['Energetic'], ['Workout'], 'Discogs'],
  ['Till I Collapse', 'Eminem ft. Nate Dogg', 'English', 'Hip Hop', 'The Eminem Show', 2002, 297, ['Energetic'], ['Workout'], 'MusicBrainz'],
  ['Can’t Hold Us', 'Macklemore & Ryan Lewis', 'English', 'Hip Hop', 'The Heist', 2011, 258, ['Energetic','Happy'], ['Workout','Party'], 'Discogs'],
  ['Stronger', 'Kanye West', 'English', 'Hip Hop', 'Graduation', 2007, 311, ['Energetic'], ['Workout'], 'MusicBrainz'],
  ['Power', 'Kanye West', 'English', 'Hip Hop', 'My Beautiful Dark Twisted Fantasy', 2010, 292, ['Energetic'], ['Workout'], 'Discogs'],
  ['Believer', 'Imagine Dragons', 'English', 'Pop rock', 'Evolve', 2017, 204, ['Energetic'], ['Workout'], 'MusicBrainz'],
  ['Radioactive', 'Imagine Dragons', 'English', 'Electronic rock', 'Night Visions', 2012, 186, ['Energetic'], ['Workout','Driving'], 'Discogs'],
  ['Natural', 'Imagine Dragons', 'English', 'Alternative rock', 'Origins', 2018, 189, ['Energetic'], ['Workout'], 'MusicBrainz'],
  ['In the End', 'Linkin Park', 'English', 'Nu metal', 'Hybrid Theory', 2000, 216, ['Energetic','Stressed'], ['Workout','Driving'], 'Discogs'],
  ['Numb', 'Linkin Park', 'English', 'Alternative rock', 'Meteora', 2003, 187, ['Energetic','Stressed'], ['Workout','Driving'], 'MusicBrainz'],
  ['Faint', 'Linkin Park', 'English', 'Nu metal', 'Meteora', 2003, 162, ['Energetic'], ['Workout'], 'Discogs'],
  ['Bleed It Out', 'Linkin Park', 'English', 'Rap rock', 'Minutes to Midnight', 2007, 164, ['Energetic'], ['Workout','Party'], 'MusicBrainz'],
  ['Smells Like Teen Spirit', 'Nirvana', 'English', 'Grunge', 'Nevermind', 1991, 301, ['Energetic','Stressed'], ['Workout','Driving'], 'Discogs'],
  ['Lithium', 'Nirvana', 'English', 'Grunge', 'Nevermind', 1991, 257, ['Energetic'], ['Workout','Driving'], 'MusicBrainz'],
  ['Come As You Are', 'Nirvana', 'English', 'Grunge', 'Nevermind', 1991, 219, ['Energetic','Relaxed'], ['Driving','Study'], 'Discogs'],
  ['Seven Nation Army', 'The White Stripes', 'English', 'Garage rock', 'Elephant', 2003, 231, ['Energetic'], ['Workout'], 'MusicBrainz'],
  ['Back in Black', 'AC/DC', 'English', 'Hard rock', 'Back in Black', 1980, 255, ['Energetic'], ['Workout','Driving'], 'Discogs'],
  ['Highway to Hell', 'AC/DC', 'English', 'Hard rock', 'Highway to Hell', 1979, 208, ['Energetic'], ['Driving','Workout'], 'MusicBrainz'],
  ['Thunderstruck', 'AC/DC', 'English', 'Hard rock', 'The Razors Edge', 1990, 292, ['Energetic'], ['Workout'], 'Discogs'],
  ['Master of Puppets', 'Metallica', 'English', 'Thrash metal', 'Master of Puppets', 1986, 515, ['Energetic'], ['Workout'], 'MusicBrainz'],
  ['Enter Sandman', 'Metallica', 'English', 'Heavy metal', 'Metallica', 1991, 331, ['Energetic'], ['Workout','Driving'], 'Discogs'],
  ['One More Time', 'Daft Punk', 'English', 'French house', 'Discovery', 2001, 320, ['Energetic','Happy'], ['Party','Workout'], 'MusicBrainz'],
  ['Harder, Better, Faster, Stronger', 'Daft Punk', 'English', 'Electro house', 'Discovery', 2001, 224, ['Energetic'], ['Workout','Party'], 'Discogs'],
  ['Around the World', 'Daft Punk', 'English', 'House', 'Homework', 1997, 429, ['Energetic','Happy'], ['Party','Workout'], 'MusicBrainz'],
  ['Animals', 'Martin Garrix', 'Electronic', 'Big room house', 'Gold Skies', 2013, 176, ['Energetic'], ['Party','Workout'], 'Discogs'],
  ['Wake Me Up', 'Avicii', 'English', 'EDM', 'True', 2013, 247, ['Energetic','Happy'], ['Party','Driving'], 'MusicBrainz'],
  ['Levels', 'Avicii', 'Electronic', 'Progressive house', 'Single', 2011, 198, ['Energetic','Happy'], ['Party','Workout'], 'Discogs'],
  ['Titanium', 'David Guetta ft. Sia', 'English', 'Electro house', 'Nothing but the Beat', 2011, 245, ['Energetic'], ['Workout','Party'], 'MusicBrainz'],
  ['Closer', 'The Chainsmokers ft. Halsey', 'English', 'Electropop', 'Collage', 2016, 244, ['Energetic','Romantic'], ['Driving','Party'], 'Discogs'],
  ['Malhari', 'Vishal Dadlani', 'Hindi', 'Bollywood', 'Bajirao Mastani', 2015, 245, ['Energetic'], ['Workout','Party'], 'MusicBrainz'],
  ['Kar Gayi Chull', 'Badshah, Fazilpuria, Sukriti Kakar & Neha Kakkar', 'Hindi', 'Bollywood', 'Kapoor & Sons', 2016, 187, ['Energetic','Happy'], ['Party'], 'Discogs'],
  ['Kala Chashma', 'Amar Arshi, Badshah & Neha Kakkar', 'Hindi', 'Bollywood', 'Baar Baar Dekho', 2016, 187, ['Energetic','Happy'], ['Party'], 'MusicBrainz'],
  ['Zinda Banda', 'Anirudh Ravichander', 'Hindi', 'Dance pop', 'Jawan', 2023, 264, ['Energetic'], ['Party','Workout'], 'Discogs'],
  ['Naatu Naatu', 'Rahul Sipligunj & Kaala Bhairava', 'Telugu', 'Folk dance', 'RRR', 2022, 215, ['Energetic','Happy'], ['Party','Workout'], 'MusicBrainz'],
  ['Hukum', 'Anirudh Ravichander', 'Tamil', 'Rock/Kuthu', 'Jailer', 2023, 207, ['Energetic'], ['Workout','Driving'], 'Discogs'],

  // --- ROMANTIC ---
  ['Perfect', 'Ed Sheeran', 'English', 'Pop ballad', '÷', 2017, 263, ['Romantic','Happy'], ['Driving','Sleep'], 'MusicBrainz'],
  ['Thinking Out Loud', 'Ed Sheeran', 'English', 'Blue-eyed soul', 'x', 2014, 281, ['Romantic','Relaxed'], ['Driving','Sleep'], 'Discogs'],
  ['Photograph', 'Ed Sheeran', 'English', 'Folk pop', 'x', 2014, 258, ['Romantic','Relaxed'], ['Study','Driving'], 'MusicBrainz'],
  ['All of Me', 'John Legend', 'English', 'R&B ballad', 'Love in the Future', 2013, 269, ['Romantic','Relaxed'], ['Sleep','Driving'], 'Discogs'],
  ['Just the Way You Are', 'Bruno Mars', 'English', 'Pop', 'Doo-Wops & Hooligans', 2010, 220, ['Romantic','Happy'], ['Driving','Party'], 'MusicBrainz'],
  ['Marry You', 'Bruno Mars', 'English', 'Pop', 'Doo-Wops & Hooligans', 2010, 230, ['Romantic','Happy'], ['Party','Driving'], 'Discogs'],
  ['Until I Found You', 'Stephen Sanchez', 'English', 'Doo-wop', 'Easy on My Eyes', 2021, 177, ['Romantic','Relaxed'], ['Driving','Sleep'], 'MusicBrainz'],
  ['Lover', 'Taylor Swift', 'English', 'Country indie', 'Lover', 2019, 221, ['Romantic','Relaxed'], ['Driving','Sleep'], 'Discogs'],
  ['Enchanted', 'Taylor Swift', 'English', 'Country pop', 'Speak Now', 2010, 352, ['Romantic','Happy'], ['Driving','Study'], 'MusicBrainz'],
  ['You Belong With Me', 'Taylor Swift', 'English', 'Country pop', 'Fearless', 2008, 231, ['Romantic','Happy'], ['Driving','Party'], 'Discogs'],
  ['Die for You', 'The Weeknd', 'English', 'R&B', 'Starboy', 2016, 260, ['Romantic'], ['Driving'], 'MusicBrainz'],
  ['Earned It', 'The Weeknd', 'English', 'Chamber pop', 'Beauty Behind the Madness', 2014, 252, ['Romantic','Relaxed'], ['Driving','Sleep'], 'Discogs'],
  ['Gerua', 'Arijit Singh & Antara Mitra', 'Hindi', 'Bollywood', 'Dilwale', 2015, 345, ['Romantic'], ['Driving'], 'MusicBrainz'],
  ['Zaalima', 'Arijit Singh & Harshdeep Kaur', 'Hindi', 'Bollywood', 'Raees', 2017, 299, ['Romantic','Relaxed'], ['Driving','Study'], 'Discogs'],
  ['Raabta (Kehte Hain Khuda Ne)', 'Arijit Singh, Shreya Ghoshal & Hamsika Iyer', 'Hindi', 'Bollywood', 'Agent Vinod', 2012, 244, ['Romantic'], ['Driving','Study'], 'MusicBrainz'],
  ['Mast Magan', 'Arijit Singh & Chinmayi Sripada', 'Hindi', 'Bollywood', '2 States', 2014, 280, ['Romantic','Relaxed'], ['Meditation','Driving'], 'Discogs'],
  ['Kesariya', 'Arijit Singh', 'Hindi', 'Bollywood', 'Brahmastra', 2022, 268, ['Romantic','Happy'], ['Driving'], 'MusicBrainz'],
  ['Apna Bana Le', 'Arijit Singh & Sachin-Jigar', 'Hindi', 'Bollywood', 'Bhediya', 2022, 261, ['Romantic','Relaxed'], ['Driving','Study'], 'Discogs'],
  ['Teri Ore', 'Shreya Ghoshal & Rahat Fateh Ali Khan', 'Hindi', 'Bollywood', 'Singh Is Kinng', 2008, 339, ['Romantic','Relaxed'], ['Driving'], 'MusicBrainz'],
  ['Deewani Mastani', 'Shreya Ghoshal', 'Hindi', 'Bollywood', 'Bajirao Mastani', 2015, 340, ['Romantic'], ['Driving','Meditation'], 'Discogs'],
  ['Agar Tum Mil Jao', 'Shreya Ghoshal', 'Hindi', 'Bollywood', 'Zeher', 2005, 361, ['Romantic','Sad'], ['Driving','Sleep'], 'MusicBrainz'],
  ['Pee Loon', 'Mohit Chauhan', 'Hindi', 'Bollywood', 'Once Upon a Time in Mumbaai', 2010, 287, ['Romantic','Relaxed'], ['Driving','Meditation'], 'Discogs'],
  ['Tum Se Hi', 'Mohit Chauhan', 'Hindi', 'Bollywood', 'Jab We Met', 2007, 321, ['Romantic','Relaxed'], ['Driving','Study'], 'MusicBrainz'],
  ['Tera Hone Laga Hoon', 'Atif Aslam & Alisha Chinai', 'Hindi', 'Bollywood', 'Ajab Prem Ki Ghazab Kahani', 2009, 300, ['Romantic','Happy'], ['Driving'], 'Discogs'],
  ['Tu Jaane Na', 'Atif Aslam', 'Hindi', 'Bollywood', 'Ajab Prem Ki Ghazab Kahani', 2009, 338, ['Romantic','Sad'], ['Driving','Study'], 'MusicBrainz'],
  ['Jeena Jeena', 'Atif Aslam', 'Hindi', 'Bollywood', 'Badlapur', 2015, 229, ['Romantic','Relaxed'], ['Driving','Sleep'], 'Discogs'],
  ['Suraj Hua Maddham', 'Sonu Nigam & Alka Yagnik', 'Hindi', 'Bollywood', 'Kabhi Khushi Kabhie Gham', 2001, 427, ['Romantic','Relaxed'], ['Driving','Meditation'], 'MusicBrainz'],
  ['Main Agar Kahoon', 'Sonu Nigam & Shreya Ghoshal', 'Hindi', 'Bollywood', 'Om Shanti Om', 2007, 310, ['Romantic','Relaxed'], ['Driving'], 'Discogs'],
  ['Tum Mile (Love Reprise)', 'Javed Ali', 'Hindi', 'Bollywood', 'Tum Mile', 2009, 301, ['Romantic','Relaxed'], ['Driving','Study'], 'MusicBrainz'],
  ['Hosanna', 'Leon D’Souza, Suzanne D’Mello & Blaaze', 'Hindi', 'Bollywood', 'Ekk Deewana Tha', 2012, 331, ['Romantic'], ['Driving'], 'Discogs'],
  ['Inkem Inkem', 'Sid Sriram', 'Telugu', 'Carnatic fusion', 'Geetha Govindam', 2018, 243, ['Romantic','Happy'], ['Driving','Study'], 'MusicBrainz'],
  ['Srivalli', 'Sid Sriram', 'Telugu', 'Melody', 'Pushpa: The Rise', 2021, 221, ['Romantic'], ['Driving'], 'Discogs'],
  ['Rowdy Baby', 'Dhanush & Dhee', 'Tamil', 'Folk pop', 'Maari 2', 2018, 284, ['Romantic','Energetic'], ['Party'], 'MusicBrainz'],
  ['Bailando', 'Enrique Iglesias ft. Descemer Bueno & Gente de Zona', 'Spanish', 'Latin pop', 'Sex and Love', 2014, 243, ['Romantic','Energetic'], ['Party','Driving'], 'Discogs'],
  ['Telepatía', 'Kali Uchis', 'Spanish', 'Dream pop', 'Sin Miedo', 2020, 160, ['Romantic','Relaxed'], ['Sleep','Driving'], 'MusicBrainz'],
  ['Boy With Luv', 'BTS ft. Halsey', 'Korean', 'Nu-disco', 'Map of the Soul: Persona', 2019, 229, ['Romantic','Happy'], ['Party','Driving'], 'Discogs'],

  // --- STRESSED (Calming / Cathartic / Relieving) ---
  ['Breathe (In the Air)', 'Pink Floyd', 'English', 'Progressive rock', 'The Dark Side of the Moon', 1973, 169, ['Stressed','Relaxed'], ['Meditation','Sleep'], 'MusicBrainz'],
  ['Comfortably Numb', 'Pink Floyd', 'English', 'Art rock', 'The Wall', 1979, 382, ['Stressed','Relaxed'], ['Driving','Meditation'], 'Discogs'],
  ['Wish You Were Here', 'Pink Floyd', 'English', 'Folk rock', 'Wish You Were Here', 1975, 334, ['Stressed','Relaxed'], ['Study','Meditation'], 'MusicBrainz'],
  ['Weight of the World', 'Keiichi Okabe', 'Japanese', 'Chamber music', 'NieR:Automata OST', 2017, 344, ['Stressed'], ['Meditation','Study'], 'Discogs'],
  ['Mad World', 'Gary Jules & Michael Andrews', 'English', 'Chamber pop', 'Donnie Darko OST', 2001, 187, ['Stressed','Sad'], ['Sleep','Study'], 'MusicBrainz'],
  ['Sound of Silence', 'Disturbed', 'English', 'Symphonic rock', 'Immortalized', 2015, 248, ['Stressed'], ['Workout','Driving'], 'Discogs'],
  ['Let It Be', 'The Beatles', 'English', 'Gospel rock', 'Let It Be', 1970, 243, ['Stressed','Relaxed'], ['Meditation','Sleep'], 'MusicBrainz'],
  ['Yesterday', 'The Beatles', 'English', 'Baroque pop', 'Help!', 1965, 125, ['Stressed','Sad'], ['Sleep','Study'], 'Discogs'],
  ['Across the Universe', 'The Beatles', 'English', 'Psychedelic folk', 'No One’s Gonna Change Our World', 1969, 228, ['Stressed','Relaxed'], ['Meditation','Sleep'], 'MusicBrainz'],
  ['Stairway to Heaven', 'Led Zeppelin', 'English', 'Hard rock', 'Led Zeppelin IV', 1971, 482, ['Stressed','Energetic'], ['Driving','Study'], 'Discogs'],
  ['Bohemian Rhapsody', 'Queen', 'English', 'Progressive rock', 'A Night at the Opera', 1975, 354, ['Stressed','Energetic'], ['Driving','Party'], 'MusicBrainz'],
  ['Under Pressure', 'Queen & David Bowie', 'English', 'Glam rock', 'Hot Space', 1981, 248, ['Stressed','Energetic'], ['Workout','Driving'], 'Discogs'],
  ['Space Oddity', 'David Bowie', 'English', 'Space rock', 'David Bowie', 1969, 315, ['Stressed','Relaxed'], ['Study','Driving'], 'MusicBrainz'],
  ['Heroes', 'David Bowie', 'English', 'Art rock', '“Heroes”', 1977, 371, ['Stressed','Energetic'], ['Driving','Workout'], 'Discogs'],
  ['Dream On', 'Aerosmith', 'English', 'Power ballad', 'Aerosmith', 1973, 267, ['Stressed','Energetic'], ['Driving','Workout'], 'MusicBrainz'],
  ['Hotel California', 'Eagles', 'English', 'Classic rock', 'Hotel California', 1976, 391, ['Stressed','Relaxed'], ['Driving'], 'Discogs'],
  ['Dust in the Wind', 'Kansas', 'English', 'Progressive folk', 'Point of Know Return', 1977, 206, ['Stressed','Relaxed'], ['Sleep','Meditation'], 'MusicBrainz'],
  ['Everybody Hurts', 'R.E.M.', 'English', 'Alternative rock', 'Automatic for the People', 1992, 318, ['Stressed','Sad'], ['Meditation','Sleep'], 'Discogs'],
  ['Losing My Religion', 'R.E.M.', 'English', 'Folk rock', 'Out of Time', 1991, 268, ['Stressed'], ['Driving','Study'], 'MusicBrainz'],
  ['Wonderwall', 'Oasis', 'English', 'Britpop', '(What’s the Story) Morning Glory?', 1995, 258, ['Stressed','Romantic'], ['Driving','Study'], 'Discogs'],
  ['Champagne Supernova', 'Oasis', 'English', 'Psychedelic rock', '(What’s the Story) Morning Glory?', 1995, 448, ['Stressed','Relaxed'], ['Meditation','Study'], 'MusicBrainz'],
  ['Don’t Look Back in Anger', 'Oasis', 'English', 'Britpop', '(What’s the Story) Morning Glory?', 1995, 288, ['Stressed','Happy'], ['Driving','Party'], 'Discogs'],
  ['Bittersweet Symphony', 'The Verve', 'English', 'Britpop', 'Urban Hymns', 1997, 358, ['Stressed','Relaxed'], ['Driving','Workout'], 'MusicBrainz'],
  ['Chasing Cars', 'Snow Patrol', 'English', 'Indie rock', 'Eyes Open', 2006, 268, ['Stressed','Romantic'], ['Sleep','Study'], 'Discogs'],
  ['How to Save a Life', 'The Fray', 'English', 'Piano rock', 'How to Save a Life', 2005, 262, ['Stressed','Sad'], ['Study','Driving'], 'MusicBrainz'],
  ['You Found Me', 'The Fray', 'English', 'Piano rock', 'The Fray', 2008, 241, ['Stressed'], ['Driving','Study'], 'Discogs'],
  ['Apologize', 'Timbaland ft. OneRepublic', 'English', 'Pop rock', 'Shock Value', 2007, 184, ['Stressed','Sad'], ['Driving','Study'], 'MusicBrainz'],
  ['In My Place', 'Coldplay', 'English', 'Alternative rock', 'A Rush of Blood to the Head', 2002, 228, ['Stressed','Relaxed'], ['Study','Driving'], 'Discogs'],
  ['Trouble', 'Coldplay', 'English', 'Alternative rock', 'Parachutes', 2000, 270, ['Stressed','Relaxed'], ['Sleep','Meditation'], 'MusicBrainz'],
  ['Aal Izz Well', 'Sonu Nigam, Swanand Kirkire & Shaan', 'Hindi', 'Bollywood', '3 Idiots', 2009, 276, ['Stressed','Happy'], ['Study','Driving'], 'Discogs'],
  ['Give Me Some Sunshine', 'Suraj Jagan & Sharman Joshi', 'Hindi', 'Bollywood', '3 Idiots', 2009, 247, ['Stressed','Sad'], ['Study','Driving'], 'MusicBrainz'],
  ['Jaane Kyun', 'Vishal Dadlani', 'Hindi', 'Bollywood', 'Dostana', 2008, 278, ['Stressed','Happy'], ['Driving','Study'], 'Discogs'],
  ['Ilahi (Reprise)', 'Mohit Chauhan', 'Hindi', 'Bollywood', 'Yeh Jawaani Hai Deewani', 2013, 213, ['Stressed','Relaxed'], ['Meditation','Study'], 'MusicBrainz'],
  ['Rubaru', 'A.R. Rahman & Naresh Iyer', 'Hindi', 'Bollywood', 'Rang De Basanti', 2006, 283, ['Stressed','Energetic'], ['Driving','Meditation'], 'Discogs'],
  ['Khoon Chala', 'Mohit Chauhan', 'Hindi', 'Bollywood', 'Rang De Basanti', 2006, 191, ['Stressed','Sad'], ['Meditation','Study'], 'MusicBrainz'],
  ['Luka Chuppi', 'Lata Mangeshkar & A.R. Rahman', 'Hindi', 'Bollywood', 'Rang De Basanti', 2006, 396, ['Stressed','Sad'], ['Sleep','Meditation'], 'Discogs'],
];

const allRaw = [...baseEntries, ...additional];
console.log('Total raw tracks:', allRaw.length);

const colors = ['sage','coral','sand','violet','blue','rose'];

const catalog = allRaw.map(([title, artist, language, genre, album, year, duration, ms, as, provider], i) => {
  const isMB = provider === 'MusicBrainz';
  const sourceUrl = isMB
    ? `https://musicbrainz.org/search?query=${encodeURIComponent(title + ' ' + artist)}&type=recording&method=indexed`
    : `https://www.discogs.com/search/?q=${encodeURIComponent(title + ' ' + artist)}&type=all`;
  return {
    id: 1001 + i,
    title,
    artist,
    language,
    genre,
    album: album || null,
    year: year || null,
    duration: duration || null,
    moodScores: Object.fromEntries(ms.map(m => [m, 0.8])),
    activityScores: Object.fromEntries(as.map(a => [a, 0.8])),
    color: colors[i % colors.length],
    source: provider,
    tagSource: i < 20 ? 'Editorial' : 'Editorial & Provider',
    isCatalog: true,
    sourceUrl,
  };
});

// Output summary counts
const moodCounts = {}, actCounts = {};
for (const song of catalog) {
  for (const m of Object.keys(song.moodScores)) moodCounts[m] = (moodCounts[m] || 0) + 1;
  for (const a of Object.keys(song.activityScores)) actCounts[a] = (actCounts[a] || 0) + 1;
}
console.log('Mood distribution:', moodCounts);
console.log('Activity distribution:', actCounts);

const code = `// Curated 216-track catalog combining MusicBrainz & Discogs metadata
export const moods = ['Happy', 'Sad', 'Relaxed', 'Energetic', 'Romantic', 'Stressed'];
export const activities = ['Study', 'Workout', 'Driving', 'Party', 'Sleep', 'Meditation'];

export const extendedCatalog = ${JSON.stringify(catalog, null, 2)};
`;

writeFileSync(resolve('src/extendedCatalog.js'), code, 'utf-8');
console.log('Saved src/extendedCatalog.js successfully with', catalog.length, 'tracks!');
